### ISSUE TITLE
Error while compiling magento 2

### ISSUE THREAD

**Issue by giusecapo** [GetResponse/GetResponse-Magento_2-Integration#2]
I get this error when I compile my Magento commerce.
This's the error:
`GetResponse\GetResponseIntegration\Helper\Data
        Incorrect dependency in class GetResponse\GetResponseIntegration\Helper\Data in /home/mobirolo/public_html/app/code/GetResponse/GetResponseIntegration/Helper/Data.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
Total Errors Count: 1`

So, I've been getting compiling error for almost 2 months, is there any remote chance to have a properly working release?
It's urgent for my client, 
Thanks.

**Comment by rkarkut** [comment]
Hi, we are working on it. I will keep you in the loop.

**Comment by giusecapo** [comment]
Do you have any news? Please let me know.

**Comment by rkarkut** [comment]
Could you try our new release? (v1.0.5) It should work properly right now.

**Comment by giusecapo** [comment]
Hi @rkarkut, unfortunately, now I have this issue
`a:4:{i:0;s:137:"Notice: Undefined index: api_key in /home/mobirolo/public_html/app/code/GetResponse/GetResponseIntegration/Block/Settings.php on line 209";i:1;s:10520:"#0 /home/mobirolo/public_html/app/code/GetResponse/GetResponseIntegration/Block/Settings.php(209): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/home/mobirolo/...', 209, Array)
`
I'm 100% sure my api key is inserted and is correct.
Please help me my client are really getting nervous about this!

**Comment by rkarkut** [comment]
Hi, we are working on it. 
I will keep you in the loop.
Best Regards.

**Comment by rkarkut** [comment]
Could you confirm it works properly right now?

**Comment by giusecapo** [comment]
I’m going to try ASAP and keep you posted :)
